spring.application.name=customer-service

# --- Database ---
spring.datasource.url=jdbc:postgresql://localhost:5432/r-bank
spring.jpa.properties.hibernate.default_schema=bank_schema
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver